# Generated by Django 4.2.7 on 2026-05-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务模块',
                'verbose_name_plural': '任务模块',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('today', '今日任务'), ('todo', '待办任务')], default='todo', max_length=10, verbose_name='任务类型')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('content', models.TextField(verbose_name='任务内容')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('postpone_tomorrow', models.BooleanField(default=False, verbose_name='推迟到明天')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.taskmodule', verbose_name='所属任务模块')),
            ],
            options={
                'verbose_name': '任务项',
                'verbose_name_plural': '任务项',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(verbose_name='序号')),
                ('hardware_version', models.CharField(blank=True, default='', max_length=100, verbose_name='硬件版型')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('android_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Android版本')),
                ('brand', models.CharField(blank=True, default='', max_length=50, verbose_name='厂商')),
                ('model', models.CharField(blank=True, default='', max_length=50, verbose_name='型号')),
                ('launcher', models.CharField(blank=True, default='', max_length=50, verbose_name='Launcher')),
                ('pir', models.BooleanField(default=False, verbose_name='PIR')),
                ('led', models.BooleanField(default=False, verbose_name='LED')),
                ('light_sensor', models.CharField(choices=[('ADCF3', 'ADCF3'), ('STK3311', 'STK3311'), ('无', '无')], default='无', max_length=20, verbose_name='光感')),
                ('wifi', models.CharField(choices=[('2.4G', '2.4G'), ('5G', '5G')], default='2.4G', max_length=10, verbose_name='WiFi')),
                ('screen_size', models.CharField(blank=True, default='', max_length=20, verbose_name='屏幕尺寸')),
                ('screen_model', models.CharField(blank=True, default='', max_length=100, verbose_name='屏幕型号')),
                ('tp', models.CharField(blank=True, default='', max_length=100, verbose_name='TP')),
                ('shell', models.CharField(blank=True, default='', max_length=100, verbose_name='壳')),
                ('project_establish_date', models.DateField(blank=True, null=True, verbose_name='立项时间')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.customer', verbose_name='所属客户')),
            ],
            options={
                'verbose_name': '项目配置',
                'verbose_name_plural': '项目配置',
                'ordering': ['serial_number'],
                'unique_together': {('customer', 'serial_number')},
            },
        ),
    ]
