# Generated by Django 4.2.7 on 2026-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('content', models.TextField(verbose_name='快照内容')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='保存时间')),
                ('content_hash', models.IntegerField(default=0, verbose_name='内容哈希')),
            ],
            options={
                'verbose_name': '历史快照',
                'verbose_name_plural': '历史快照',
                'ordering': ['-saved_at'],
            },
        ),
    ]
