# Generated by Django 4.2.7 on 2026-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='version',
            field=models.PositiveIntegerField(default=0, verbose_name='版本号'),
        ),
    ]
