# Generated by Django 4.2.7 on 2026-07-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_taskitem_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(max_length=500, verbose_name='链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户APK',
                'verbose_name_plural': '客户APK',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
