# Generated by Django 4.2.7 on 2026-07-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apklink',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='链接'),
        ),
    ]
