# Generated by Django 4.2.7 on 2026-07-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_apklink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='postponed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='标记推迟时间'),
        ),
    ]
